### ISSUE TITLE
An user per client and only allow them to execute retrieve_crypto_key 

### ISSUE THREAD

**Issue by 459below** [fetzerms/cryptboot-ssh#1]
I may have overlooked something, since it's very late. However at my current state of understanding it would seem that, if one can steal the private key of one of the clients, they could log on as user@keyvm and download all the keys. So if the user "user" is able to spawn a full shell, every client is granted access to all the keys.

**Comment by fetzerms** [comment]
With the "command=" directive in the authorized_keys-file, the execution of a specific command (which retrieves the crypt keys) is enforced. The execution of other commands is not possible. Hence it is not possible to spawn a shell using a client ssh key.

See the command= part in the manual: https://www.freebsd.org/cgi/man.cgi?sshd(8)#AUTHORIZED_KEYS%09FILE_FORMAT

Does this answer your question?

**Comment by 459below** [comment]
Ah, well my apologies. I didn't know this directive. Thanks for the clarification. That is good to know. I would suggest however to mention that explicitly in the comments on line 150 of README.md somewhere. To emphasize that it has been thought of.

**Comment by fetzerms** [comment]
Thank for the feedback and contribution. I added further explanations, regarding the command directive.
