### ISSUE TITLE
Support fallback to askpass in case the cryptvm cannot be reached

### ISSUE THREAD

**Issue by sscheib** [fetzerms/cryptboot-ssh#10]
If the keyserver is not reachable for whatever reason there is no possibility to manually enter the luks keyphrase.
When connected to the VM, which is not able to reach the keyserver (clientVM), the following error happens:
`~ # cryptroot-unlock 
Error: Timeout reached while waiting for askpass.`

Is this an intended behaviour? I was under the impression, that whenever the keyserver is not reachable, there is always the possibility to manually enter the password.

The problem looks like the following on the clientVM:
![clientvm](https://user-images.githubusercontent.com/37306894/38767352-da0a5382-3fdf-11e8-8f12-231fd5fb6532.png)

**Comment by 459below** [comment]
Do you know, that you can just
`cryptsetup open /dev/sda1 root-hdd
*ENTER PASSWORD*
exit`

and it will just continue as usual?

It should say this in the documentation. Granted it takes it takes a while until the process will drop you to the shell, but you will always get back into the system.

However this is one reason why I'm trying to setup a [keyserver on Android](https://github.com/fetzerms/cryptboot-ssh/issues/11).

**Comment by 459below** [comment]
Reopening, since it needs another PR for cryptsetup to work in initramfs.
Sorry, I always set the CRYPTSETUP=y parameter and took it for granted.
